// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2mliNoMy2bmq2OcxKDiqAwD1Q20Gy4M',
    appId: '1:828754552495:web:9fbe49bb6325f86445d65a',
    messagingSenderId: '828754552495',
    projectId: 'urbiconnect-a6849',
    authDomain: 'urbiconnect-a6849.firebaseapp.com',
    storageBucket: 'urbiconnect-a6849.firebasestorage.app',
    measurementId: 'G-CXSG3PFP3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wbzeDsA3QgVcYfyKLPSMoCcUVHqyseA',
    appId: '1:828754552495:android:67c45e362579ba9345d65a',
    messagingSenderId: '828754552495',
    projectId: 'urbiconnect-a6849',
    storageBucket: 'urbiconnect-a6849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt983BLDzjlOxgqnb32MQxZM3YTOIG39k',
    appId: '1:828754552495:ios:b8ae856ce922e36045d65a',
    messagingSenderId: '828754552495',
    projectId: 'urbiconnect-a6849',
    storageBucket: 'urbiconnect-a6849.firebasestorage.app',
    iosBundleId: 'com.example.urbiConnect',
  );
}
