name: urbi_connect
description: Aplicación de gestión de incidencias ciudadanas para el pueblo de Cantillana.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.0

  # Utilidades y UI
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  path_provider: ^2.1.3
  share_plus: ^7.2.1
  url_launcher: ^6.3.1

  # Hardware y Mapas
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  http: ^1.2.1
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
