name: urbi_connect
description: Aplicación de gestión de incidencias ciudadanas para el pueblo de Cantillana.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # Utilidades y UI
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.0

  # Hardware y Mapas
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
